version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/webservice
hooks:
#  ApplicationStop:
#    - location: ./scripts/applicationStop.sh
#      timeout: 180
#      runas: root
  BeforeInstall:
    - location: ./scripts/beforeInstall.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: ./scripts/afterInstall.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: ./scripts/applicationStart.sh
      timeout: 180
      runas: root