spring:
  application:
    name: assignment2
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
#    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}  #   mvn test -Dspring.datasource.password=<>
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
server:
  port: 8081

logging.config:
  classpath: log4j2.xml

cloud:
  aws:
    bucketname: ${S3_BUCKETNAME}
#encryption:
#  salt: ${salt}
#  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#  spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#  spring.jpa.hibernate.ddl-auto=update
#  spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#  spring.datasource.url=jdbc:mysql://localhost:3306/test
#  spring.datasource.username=test
#  spring.datasource.password=

