name: CI
on:
  push:
    branches: [feature/a4]
jobs:
#  build:
#    name: CheckStatus
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 8
#        uses: actions/setup-java@v2
#        with:
#          java-version: '8'
#          distribution: 'adopt'
#      - name: Run Tests
#        run: mvn --batch-mode --update-snapshots test
#      - name: Build with Maven
#        run: mvn --batch-mode --update-snapshots install
#  zip_code:
##    needs: build
#    runs-on: ubuntu-latest
#    name: Zip Application Code
#    steps:
#      - name: Step 1 - Checkout code
#        uses: actions/checkout@v2
#      - name: zip files
#        run: zip -r webservice.zip ./
#      - name: print contents
#        run: echo $(ls)
  validation:
#    needs: zip_code
    runs-on: ubuntu-latest
    name: Packer Template Validation
    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v2
      - name: zip files
        run: zip -r webservice.zip ./
      - name: print contents
        run: echo $(ls)
#      - name: Action - Checkout
#        uses: actions/checkout@v2
      - name: Init Packer
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: amisetup.pkr.hcl
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -var-file=amisetup.auto.pkrvars.hcl
          target: amisetup.pkr.hcl
#  zip_code:
#    needs: validation
#    runs-on: ubuntu-latest
#    name: Zip Application Code
#    steps:
#      - name: Step 1 - Checkout code
#        uses: actions/checkout@v2
#      - name: zip files
#        run: zip -r webservice.zip ./
  packer_build:
    needs: validation
    runs-on: ubuntu-latest
    name: Packer Build AMI
    steps:
#      - name: Step 1 - Checkout code
#        uses: actions/checkout@v2
      - name: Step 2 - Packer Init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: amisetup.pkr.hcl
      - name: Step 3 - Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: -var=AWS_ACCESSKEY=${{ secrets.AWS_ACCESS_KEY_ID }} -var=AWS_SECTRET_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} -var-file=amisetup.auto.pkrvars.hcl -on-error=abort
          target: amisetup.pkr.hcl
        env:
          PACKER_LOG: 1